name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'src/**/*.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
    
    - name: Generate API documentation
      run: |
        python scripts/generate_api_docs.py
    
    - name: Update tool documentation
      run: |
        python scripts/update_tool_docs.py
    
    - name: Build documentation
      run: |
        mkdocs build --clean
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: docs.omie-mcp.uptax.com
    
    - name: Check for broken links
      run: |
        pip install linkchecker
        linkchecker ./site/index.html

  validate-markdown:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Lint markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        config: '.markdownlint.yml'
        args: 'docs/'
    
    - name: Check spelling
      uses: streetsidesoftware/cspell-action@v2
      with:
        files: 'docs/**/*.md'
        config: '.cspell.json'